# Generated by Django 2.2 on 2021-05-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_contact_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, null=True)),
                ('location', models.CharField(max_length=200)),
                ('discription', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='image')),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('C', 'Courses'), ('H', 'Help')], max_length=10, null=True)),
            ],
        ),
    ]
